name: Build and Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Install Node Modules
        run: |
          cd front-end
          npm ci
          cd ../resume
          npm ci

      - name: Build Front-End
        run: |
          cd front-end
          npm run build

      - name: Build Resume
        run: |
          cd resume
          npm run build

      - name: Copy Files to Public Directory
        run: |
          mkdir public
          cp -r front-end/dist/front-end/browser ./public
          cp resume/resume-* ./public

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          cname: willrwarner.dev
